// <auto-generated />
using System;
using Exercice_Form.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exercice_Form.Migrations
{
    [DbContext(typeof(ExeDbContext))]
    [Migration("20210212192025_SeedAjoutPays")]
    partial class SeedAjoutPays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exercice4_Formulaire.Models.Departement", b =>
                {
                    b.Property<int>("DepartementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Budget")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartementId");

                    b.ToTable("Departements");
                });

            modelBuilder.Entity("Exercice4_Formulaire.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<bool>("EstEnEmploi")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaysId")
                        .HasColumnType("int");

                    b.Property<int>("Salaire")
                        .HasColumnType("int");

                    b.HasKey("EmployeId");

                    b.HasIndex("DepartementId");

                    b.HasIndex("PaysId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("Exercice4_Formulaire.Models.Pays", b =>
                {
                    b.Property<int>("PaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Superficie")
                        .HasColumnType("int");

                    b.HasKey("PaysId");

                    b.ToTable("Pays");

                    b.HasData(
                        new
                        {
                            PaysId = 1,
                            Nom = "Afghanistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 2,
                            Nom = "Albanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 3,
                            Nom = "Antarctique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 4,
                            Nom = "Algérie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 5,
                            Nom = "Samoa Américaines",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 6,
                            Nom = "Andorre",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 7,
                            Nom = "Angola",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 8,
                            Nom = "Antigua-et-Barbuda",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 9,
                            Nom = "Azerbaïdjan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 10,
                            Nom = "Argentine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 11,
                            Nom = "Australie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 12,
                            Nom = "Autriche",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 13,
                            Nom = "Bahamas",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 14,
                            Nom = "Bahreïn",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 15,
                            Nom = "Bangladesh",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 16,
                            Nom = "Arménie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 17,
                            Nom = "Barbade",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 18,
                            Nom = "Belgique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 19,
                            Nom = "Bermudes",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 20,
                            Nom = "Bhoutan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 21,
                            Nom = "Bolivie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 22,
                            Nom = "Bosnie-Herzégovine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 23,
                            Nom = "Botswana",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 24,
                            Nom = "Île Bouvet",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 25,
                            Nom = "Brésil",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 26,
                            Nom = "Belize",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 27,
                            Nom = "Territoire Britannique de l'Océan Indien",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 28,
                            Nom = "Îles Salomon",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 29,
                            Nom = "Îles Vierges Britanniques",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 30,
                            Nom = "Brunéi Darussalam",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 31,
                            Nom = "Bulgarie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 32,
                            Nom = "Myanmar",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 33,
                            Nom = "Burundi",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 34,
                            Nom = "Bélarus",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 35,
                            Nom = "Cambodge",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 36,
                            Nom = "Cameroun",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 37,
                            Nom = "Canada",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 38,
                            Nom = "Cap-vert",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 39,
                            Nom = "Îles Caïmanes",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 40,
                            Nom = "République Centrafricaine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 41,
                            Nom = "Sri Lanka",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 42,
                            Nom = "Tchad",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 43,
                            Nom = "Chili",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 44,
                            Nom = "Chine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 45,
                            Nom = "Taïwan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 46,
                            Nom = "Île Christmas",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 47,
                            Nom = "Îles Cocos (Keeling)",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 48,
                            Nom = "Colombie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 49,
                            Nom = "Comores",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 50,
                            Nom = "Mayotte",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 51,
                            Nom = "République du Congo",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 52,
                            Nom = "République Démocratique du Congo",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 53,
                            Nom = "Îles Cook",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 54,
                            Nom = "Costa Rica",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 55,
                            Nom = "Croatie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 56,
                            Nom = "Cuba",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 57,
                            Nom = "Chypre",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 58,
                            Nom = "République Tchèque",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 59,
                            Nom = "Bénin",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 60,
                            Nom = "Danemark",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 61,
                            Nom = "Dominique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 62,
                            Nom = "République Dominicaine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 63,
                            Nom = "Équateur",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 64,
                            Nom = "El Salvador",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 65,
                            Nom = "Guinée Équatoriale",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 66,
                            Nom = "Éthiopie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 67,
                            Nom = "Érythrée",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 68,
                            Nom = "Estonie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 69,
                            Nom = "Îles Féroé",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 70,
                            Nom = "Îles (malvinas) Falkland",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 71,
                            Nom = "Géorgie du Sud et les Îles Sandwich du Sud",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 72,
                            Nom = "Fidji",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 73,
                            Nom = "Finlande",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 74,
                            Nom = "Îles Åland",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 75,
                            Nom = "France",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 76,
                            Nom = "Guyane Française",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 77,
                            Nom = "Polynésie Française",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 78,
                            Nom = "Terres Australes Françaises",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 79,
                            Nom = "Djibouti",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 80,
                            Nom = "Gabon",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 81,
                            Nom = "Géorgie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 82,
                            Nom = "Gambie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 83,
                            Nom = "Territoire Palestinien Occupé",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 84,
                            Nom = "Allemagne",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 85,
                            Nom = "Ghana",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 86,
                            Nom = "Gibraltar",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 87,
                            Nom = "Kiribati",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 88,
                            Nom = "Grèce",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 89,
                            Nom = "Groenland",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 90,
                            Nom = "Grenade",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 91,
                            Nom = "Guadeloupe",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 92,
                            Nom = "Guam",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 93,
                            Nom = "Guatemala",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 94,
                            Nom = "Guinée",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 95,
                            Nom = "Guyana",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 96,
                            Nom = "Haïti",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 97,
                            Nom = "Îles Heard et Mcdonald",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 98,
                            Nom = "Saint-Siège (état de la Cité du Vatican)",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 99,
                            Nom = "Honduras",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 100,
                            Nom = "Hong-Kong",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 101,
                            Nom = "Hongrie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 102,
                            Nom = "Islande",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 103,
                            Nom = "Inde",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 104,
                            Nom = "Indonésie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 105,
                            Nom = "République Islamique d'Iran",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 106,
                            Nom = "Iraq",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 107,
                            Nom = "Irlande",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 108,
                            Nom = "Israël",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 109,
                            Nom = "Italie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 110,
                            Nom = "Côte d'Ivoire",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 111,
                            Nom = "Jamaïque",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 112,
                            Nom = "Japon",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 113,
                            Nom = "Kazakhstan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 114,
                            Nom = "Jordanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 115,
                            Nom = "Kenya",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 116,
                            Nom = "République Populaire Démocratique de Corée",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 117,
                            Nom = "République de Corée",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 118,
                            Nom = "Koweït",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 119,
                            Nom = "Kirghizistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 120,
                            Nom = "République Démocratique Populaire Lao",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 121,
                            Nom = "Liban",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 122,
                            Nom = "Lesotho",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 123,
                            Nom = "Lettonie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 124,
                            Nom = "Libéria",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 125,
                            Nom = "Jamahiriya Arabe Libyenne",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 126,
                            Nom = "Liechtenstein",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 127,
                            Nom = "Lituanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 128,
                            Nom = "Luxembourg",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 129,
                            Nom = "Macao",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 130,
                            Nom = "Madagascar",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 131,
                            Nom = "Malawi",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 132,
                            Nom = "Malaisie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 133,
                            Nom = "Maldives",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 134,
                            Nom = "Mali",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 135,
                            Nom = "Malte",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 136,
                            Nom = "Martinique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 137,
                            Nom = "Mauritanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 138,
                            Nom = "Maurice",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 139,
                            Nom = "Mexique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 140,
                            Nom = "Monaco",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 141,
                            Nom = "Mongolie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 142,
                            Nom = "République de Moldova",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 143,
                            Nom = "Montserrat",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 144,
                            Nom = "Maroc",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 145,
                            Nom = "Mozambique",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 146,
                            Nom = "Oman",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 147,
                            Nom = "Namibie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 148,
                            Nom = "Nauru",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 149,
                            Nom = "Népal",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 150,
                            Nom = "Pays-Bas",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 151,
                            Nom = "Antilles Néerlandaises",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 152,
                            Nom = "Aruba",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 153,
                            Nom = "Nouvelle-Calédonie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 154,
                            Nom = "Vanuatu",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 155,
                            Nom = "Nouvelle-Zélande",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 156,
                            Nom = "Nicaragua",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 157,
                            Nom = "Niger",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 158,
                            Nom = "Nigéria",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 159,
                            Nom = "Niué",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 160,
                            Nom = "Île Norfolk",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 161,
                            Nom = "Norvège",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 162,
                            Nom = "Îles Mariannes du Nord",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 163,
                            Nom = "Îles Mineures Éloignées des États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 164,
                            Nom = "États Fédérés de Micronésie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 165,
                            Nom = "Îles Marshall",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 166,
                            Nom = "Palaos",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 167,
                            Nom = "Pakistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 168,
                            Nom = "Panama",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 169,
                            Nom = "Papouasie-Nouvelle-Guinée",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 170,
                            Nom = "Paraguay",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 171,
                            Nom = "Pérou",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 172,
                            Nom = "Philippines",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 173,
                            Nom = "Pitcairn",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 174,
                            Nom = "Pologne",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 175,
                            Nom = "Portugal",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 176,
                            Nom = "Guinée-Bissau",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 177,
                            Nom = "Timor-Leste",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 178,
                            Nom = "Porto Rico",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 179,
                            Nom = "Qatar",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 180,
                            Nom = "Réunion",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 181,
                            Nom = "Roumanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 182,
                            Nom = "Fédération de Russie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 183,
                            Nom = "Rwanda",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 184,
                            Nom = "Sainte-Hélène",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 185,
                            Nom = "Saint-Kitts-et-Nevis",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 186,
                            Nom = "Anguilla",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 187,
                            Nom = "Sainte-Lucie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 188,
                            Nom = "Saint-Pierre-et-Miquelon",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 189,
                            Nom = "Saint-Vincent-et-les Grenadines",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 190,
                            Nom = "Saint-Marin",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 191,
                            Nom = "Sao Tomé-et-Principe",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 192,
                            Nom = "Arabie Saoudite",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 193,
                            Nom = "Sénégal",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 194,
                            Nom = "Seychelles",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 195,
                            Nom = "Sierra Leone",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 196,
                            Nom = "Singapour",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 197,
                            Nom = "Slovaquie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 198,
                            Nom = "Viet Nam",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 199,
                            Nom = "Slovénie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 200,
                            Nom = "Somalie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 201,
                            Nom = "Afrique du Sud",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 202,
                            Nom = "Zimbabwe",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 203,
                            Nom = "Espagne",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 204,
                            Nom = "Sahara Occidental",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 205,
                            Nom = "Soudan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 206,
                            Nom = "Suriname",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 207,
                            Nom = "Svalbard etÎle Jan Mayen",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 208,
                            Nom = "Swaziland",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 209,
                            Nom = "Suède",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 210,
                            Nom = "Suisse",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 211,
                            Nom = "République Arabe Syrienne",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 212,
                            Nom = "Tadjikistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 213,
                            Nom = "Thaïlande",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 214,
                            Nom = "Togo",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 215,
                            Nom = "Tokelau",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 216,
                            Nom = "Tonga",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 217,
                            Nom = "Trinité-et-Tobago",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 218,
                            Nom = "Émirats Arabes Unis",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 219,
                            Nom = "Tunisie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 220,
                            Nom = "Turquie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 221,
                            Nom = "Turkménistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 222,
                            Nom = "Îles Turks et Caïques",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 223,
                            Nom = "Tuvalu",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 224,
                            Nom = "Ouganda",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 225,
                            Nom = "Ukraine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 226,
                            Nom = "L'ex-République Yougoslave de Macédoine",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 227,
                            Nom = "Égypte",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 228,
                            Nom = "Royaume-Uni",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 229,
                            Nom = "Île de Man",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 230,
                            Nom = "République-Unie de Tanzanie",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 231,
                            Nom = "États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 232,
                            Nom = "Îles Vierges des États-Unis",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 233,
                            Nom = "Burkina Faso",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 234,
                            Nom = "Uruguay",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 235,
                            Nom = "Ouzbékistan",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 236,
                            Nom = "Venezuela",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 237,
                            Nom = "Wallis et Futuna",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 238,
                            Nom = "Samoa",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 239,
                            Nom = "Yémen",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 240,
                            Nom = "Serbie-et-Monténégro",
                            Superficie = 0
                        },
                        new
                        {
                            PaysId = 241,
                            Nom = "Zambie",
                            Superficie = 0
                        });
                });

            modelBuilder.Entity("Exercice4_Formulaire.Models.Employe", b =>
                {
                    b.HasOne("Exercice4_Formulaire.Models.Departement", "Departement")
                        .WithMany("Employes")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exercice4_Formulaire.Models.Pays", "PaysOrigine")
                        .WithMany("Employes")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("PaysOrigine");
                });

            modelBuilder.Entity("Exercice4_Formulaire.Models.Departement", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("Exercice4_Formulaire.Models.Pays", b =>
                {
                    b.Navigation("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
